version: '3'

volumes:
  static: {}
  nginx: {}

services:

  nginx:
    image: nginx:latest
    container_name: time-recording-nginx
    ports:
      - 80:8000
    volumes:
      - static:/static/
      - nginx:/etc/nginx/conf.d/
    depends_on:
      - web

  web:
    image: achmanngopf/time-recording-django
    container_name: timerecording-web
    environment:
      DJANGO_CONFIGURATION: Prod
      DJANGO_SETTINGS_MODULE: timerecording.settings
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - static:/static/
      - nginx:/config/nginx/
    depends_on:
      - db

  db:
    image: postgres:9.6
    container_name: timerecording-db
    ports:
      - 5432:5432
    volumes:
      - ./db/prod/pgdata:/var/lib/postgresql/data/
      - ./db/prod/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=timerecording
      - POSTGRES_PASSWORD=${DB_PASSWORD}


  db-backup:
    image: jmcarbo/docker-postgres-backup
    container_name: timerecording-db-backup
    volumes:
      - ./db/prod/backup:/backup
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: timerecording
      CRON_TIME: "0 2 * * *"
      MAX_BACKUPS: 100
