version: '3'

volumes:
  static: {}

services:

  nginx:
    image: nginx:latest
    container_name: timerecording_nginx
    ports:
      - 80:8000
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/static
    depends_on:
      - web

  web:
    image: achmanngopf/time-recording-django
    container_name: timerecording_web
    environment:
      - DJANGO_CONFIGURATION=Prod
      - DJANGO_SETTINGS_MODULE=timerecording.settings
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - static:/static
    depends_on:
      - db

  db:
    image: postgres:10
    container_name: timerecording_db
    ports:
      - 5432:5432
    volumes:
      - ./db/prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=timerecording
      - POSTGRES_PASSWORD=${DB_PASSWORD}