# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('amount', models.FloatField(verbose_name='Betrag')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nachname')),
                ('cost_rate', models.IntegerField(default=80, verbose_name='Kostensatz')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
            },
        ),
        migrations.CreateModel(
            name='LabourCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('duration', models.IntegerField(verbose_name='Dauer (Minuten)')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recorder.Comment', verbose_name='Kommentar')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recorder.Employee')),
            ],
            options={
                'verbose_name': 'Arbeitsaufwand',
                'verbose_name_plural': 'Arbeitsaufwände',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=-1, verbose_name='Maschinennummer')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('assigned_employees', models.ManyToManyField(related_name='machines', to='recorder.Employee')),
            ],
            options={
                'verbose_name': 'Maschine',
                'verbose_name_plural': 'Maschinen',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Maschinentyp',
                'verbose_name_plural': 'Maschinentypen',
            },
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recorder.Machine', verbose_name='Maschine')),
            ],
            options={
                'verbose_name': 'Materialaufwand',
                'verbose_name_plural': 'Materialaufwände',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1, verbose_name='Projektnummer')),
                ('description', models.CharField(max_length=200, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.Project', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recorder.MachineType', verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='labourcost',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recorder.Machine', verbose_name='Maschine'),
        ),
        migrations.AddField(
            model_name='earning',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.Project', verbose_name='Projekt'),
        ),
    ]
