# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='machines', to='recorder.Employee'),
        ),
    ]
