# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earning',
            options={'verbose_name': 'Erlös', 'verbose_name_plural': 'Erlöse'},
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(verbose_name='Projektnummer'),
        ),
    ]
