# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20180302_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earning',
            name='amount',
        ),
        migrations.AddField(
            model_name='earning',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingefügt'),
        ),
        migrations.AddField(
            model_name='earning',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet'),
        ),
        migrations.AddField(
            model_name='employee',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingefügt'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet'),
        ),
        migrations.AddField(
            model_name='labourcost',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingefügt'),
        ),
        migrations.AddField(
            model_name='labourcost',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet'),
        ),
        migrations.AddField(
            model_name='machine',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingefügt'),
        ),
        migrations.AddField(
            model_name='machine',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet'),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingefügt'),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet'),
        ),
        migrations.AddField(
            model_name='project',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingefügt'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet'),
        ),
    ]
