# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20171205_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Kostenträger', 'verbose_name_plural': 'Kostenträger'},
        ),
        migrations.AddField(
            model_name='earning',
            name='type',
            field=models.CharField(choices=[('a', 'Maschine'), ('b', 'Ersatzteil'), ('c', 'Service'), ('d', 'Sonstiges')], default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recorder.Machine', verbose_name='Kostenträger'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.IntegerField(verbose_name='Maschinennummer'),
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recorder.Machine', verbose_name='Kostenträger'),
        ),
    ]
