# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_auto_20180104_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='type',
            field=models.CharField(choices=[('a', 'Maschine'), ('b', 'Ersatzteil'), ('c', 'Service'), ('d', 'Sonstiges')], default='d', max_length=1, verbose_name='Typ'),
        ),
    ]
